server:
  port: 8088
logging:
  file: logs/spring-boot-logging.log

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Rmal9611@
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
